### ISSUE TITLE
Extra error message trying to stop a non-existent or erroneous minikube

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rd#121]
On a pristine machine, with no minikube installed, on shutdown I get an error dialog telling me "Error stopping minikube" . Of course there is, it was never started.

The message should be squelched.

**Comment by mattfarina** [comment]
@ericpromislow minikube is used internally. Once you run `npm run setupmac` minikube is installed. And it's bundled in the build of rd. Error stopping minikube is from our internal use of it.

**Comment by ericpromislow** [comment]
Reasonable to leave this behavior
