### ISSUE TITLE
Nothing is persisted when restarting rd

### ISSUE THREAD

**Issue by troytop** [rancher-sandbox/rd#131]
I built rd on Mac OS X 10.14.6 (node v15.8.0) and ran it with `npm run dev`. Everything came up normally and I installed some Helm charts (Carrier via the carrier cli and Aerospike via `helm`).

I stopped rancher desktop using the "Quit Rancher Desktop" menu item. 

After starting it again with `npm run dev` I notice that my deployments are gone along with a test namespace I created. As far as I can tell, nothing is persisted when you restart.

**Comment by jandubois** [comment]
I can confirm that apps are gone after the VM has been stopped and restarted. In addition I noticed that the hostpath provisioner stores the data under `/tmp`, which is using `tmpfs`, so won't survive a reboot either.

Given that we are going to move away from minikube for provisioning the VM, I don't see the point in fixed the bug right now, but we should keep the issue open to make sure the new solution will not inherit the problem.

**Comment by mook-as** [comment]
Minikube is gone, things are preserved now.
