### ISSUE TITLE
Need more resilience for managing the rancher install

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rd#150]
* If some of the helm charts are still installed, both install and uninstall will fail
* If k8s is in an ERROR state, it should let the user know that (beyond the red-colored icon), and offer to fix whatever the problem is rather than do a reset.

**Comment by mattfarina** [comment]
As we are no longer going to offer Rancher as part of the experience I'm going to close this issue.

If we bring it back later in some form we can bring this up again.
