### ISSUE TITLE
Connect minikube replacement to UI/biz logic

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#159]
Once minikube is moved to a hyperkit replacement, the replacement will need to be wired into the business logic/UI in JS/typescript. This issue is for that step.

**Comment by jandubois** [comment]
Updated releases:

https://github.com/rancher-sandbox/docker-machine-driver-hyperkit/releases/tag/v2.0.0-alpha.2
https://github.com/rancher-sandbox/boot2tcl/releases/tag/v1.1.1
https://github.com/rancher/kim/releases/tag/v0.1.0-alpha.10

I've tested all of them together, and KIM installs and build images as expected.
