### ISSUE TITLE
Build on macOS has white screen

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#162]
<img width="1052" alt="Screen Shot 2021-04-02 at 9 47 16 AM" src="https://user-images.githubusercontent.com/62991/113427802-ae68fb00-93a3-11eb-801e-bfc9b9448fa5.png">

I found then when running `npm run build` myself and then found it was the case with the builds from CI.

**Comment by ericpromislow** [comment]
In PR #181

**Comment by mattfarina** [comment]
Closing as the PR was merged
