### ISSUE TITLE
Test that we still come up after reboot on Windows

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rd#175]
Deploy Bitnami Wordpress and create a post, then take things down and see that we still have stuff written down.

**Comment by mook-as** [comment]
This seems to work:
- Deploy `bitnami/wordpress`. (Make sure to delete any PVCs ahead to time, the mariadb chart is _really_ bad about erroring out if you had an old DB with a different password)
- Do the port forwarding as described in the chart: `kubectl port-forward --namespace default svc/wp-wordpress 80:80`
- Decode the `wordpress-password` secret 
- Login at `http://localhost/admin`
- Create a post
- Quit rd
- Run `npm run dev` again
- Do the port forwarding again
- Check that `http://localhost/` shows the new post.

**Comment by mook-as** [comment]
This also works for mac with hyperkit.
