### ISSUE TITLE
Cache boot2tcl.iso on local filesystem (or bundle it with the app)

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rd#203]
Right now we will dowload the image from Github every time a machine is created (which currently also happens when you downgrade k8s, see #201).

Since we don't have any mechanism to upgrade to a newer ISO without upgrading RD itself, maybe it would be easiest to bundle the ima inside the app. That would also improve first-start experience.

Alternatively, the "obvious" location to cache the image would be `~/Library/State/rancher-desktop/driver/cache/boot2tcl.iso`. This is where the `boot2docker.iso` would be placed when you don't specify the `--iso-url` parameter. But I think bundling the ISO is preferable.

**Comment by mook-as** [comment]
Hmm, we should already be caching it [here](https://github.com/rancher-sandbox/rd/blob/3b3e58fee49263a29f456eef642f47b88de98094/src/k8s-engine/hyperkit.ts#L173-L176).  It's in the terribly non-intuitive name of `image.iso`, though.

Bundling it would probably make sense.

**Comment by jandubois** [comment]
Closing this issue because we are already caching the ISO, and for bundling we have #224
