### ISSUE TITLE
RD is not a singleton app on Windows

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rd#238]
When RD is already running (on Windows), and I click the "Rancher Desktop" shortcut icon on the desktop, it starts up a second instance.

That instance will fail because it cannot startup kubernetes, but also seems to kill the already running instance.

It should not be possible to launch more than a single copy of RD on a host.

**Comment by mattfarina** [comment]
I think the same problem applies to windows as well.

**Comment by jandubois** [comment]
> I think the same problem applies to windows as well.

This is *just* a Windows issue; on macOS all GUI apps are singletons by default...

**Comment by jandubois** [comment]
> This is _just_ a Windows issue; on macOS all GUI apps are singletons by default...

As @mattfarina pointed out, this assumption does not hold when you launch the GUI application manually from the terminal and not via Finder/launchd, so the code should also cover the macOS use case.
