### ISSUE TITLE
Windows taskbar icons remain for RD instances that are no longer running

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rd#239]
See screenshot:

<img width="120" alt="Screen Shot 2021-05-03 at 10 02 45 AM" src="https://user-images.githubusercontent.com/78947/116907765-df348e00-abf6-11eb-9a01-95b0f9161859.png">

**Comment by mook-as** [comment]
This _should_ only happen if it crashes instead of exiting normally. Note that _should_ doesn't always mean it happens ;)  In that case, generally mouse-overing the icons will make them go away (because Explorer realizes it can't send messages to the window to handle mouse movement).

**Comment by jandubois** [comment]
> generally mouse-overing the icons will make them go away

Not happening for me; they still seem to be functional: I can expand the menu and see e.g. the current kubernetes context:

<img width="419" alt="Screen Shot 2021-05-03 at 10 09 45 AM" src="https://user-images.githubusercontent.com/78947/116908517-de502c00-abf7-11eb-9472-5206e3b85607.png">

It turns out the app instances are still running in the background, they just don't seem to have any GUI presence anymore beyond the (hidden) notification icons; the normal app icons are gone:

<img width="947" alt="Screen Shot 2021-05-03 at 10 12 30 AM" src="https://user-images.githubusercontent.com/78947/116908947-5cacce00-abf8-11eb-9dd9-6815608997ea.png">

I wonder if this is related to me clicking on the `X` close icon on the top right corner instead of picking `File | Exit` from the menu (which doesn't seem to have a keyboard shortcut, but maybe that is intentional?).

**Comment by jandubois** [comment]
It turns out that I have about 15 of these processes on my machine, and I can't seem to terminate them with `End task`.

Also any new RD I start now cannot start kubernetes anymore. I guess I could stop the `k3s` distro to kill the currently running instance, but this is a situation a user should never get into.

**Comment by jandubois** [comment]
> I can't seem to terminate them with `End task`.

Well, it turns out if you are very patient, and willing to `terminate task` multiple times, you eventually get all tasks cleaned up, and *then* you can hover over the notification icons, and they too will vanish...

**Comment by mook-as** [comment]
Right; on Windows, closing the Window does _not_ terminate Rancher Desktop. (Actually, it doesn't on Mac either, though it does leave the dock icon.)

You'd need to quit by right-clicking and selecting Exit, though I think we may have issues where failing to stop k3s (possibly because we hit other errors and it never started) will prevent exit.

**Comment by jandubois** [comment]
I'm closing this issue because the multiple notification icons are covered by #238, and the general UX of closing the window vs. closing the app should be discussed in #243.

The is still a possibility that a notification icon remains in the overflow area when RD itself has terminated abnormally, but there isn't really anything we can about it, and it is self-healing once the user hovers the mouse pointer over the orphaned icon.
