### ISSUE TITLE
rancher-desktop error on start - A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by abonillabeeche** [rancher-sandbox/rd#246]
Mac Big Sur 11.3 - intel

A JavaScript error occurred in the main process
Uncaught Exception:
Error: spawn /Applications/rancher-desktop.app/Contents/Resources/resources/darwin/minikube ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
at onErrorNT (internal/child_process.js:469:16)
at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by jandubois** [comment]
This is rather curious; are you sure you are not running one of the pre-alpha versions?

Red flags from your error message:

* The 0.1.0 alpha release is called `Rancher Desktop.app` and not `rancher-desktop.app`.
* It is not using `minikube` but `hyperkit` directly.

I would recommend to delete `/Applications/rancher-desktop.app` and try again. Please re-open if the error persists.
