### ISSUE TITLE
Is Apple M1 supported yet?

### ISSUE THREAD

**Issue by alexellis** [rancher-sandbox/rd#247]
Hi folks, excited to try this out, but is my Apple M1 supported yet?

<img width="943" alt="Screenshot 2021-05-04 at 08 56 29" src="https://user-images.githubusercontent.com/6358735/116974852-a825b180-acb6-11eb-87c6-f4d48cf8ac47.png">

I couldn't find any notes about this, but I may have missed them. 

Alex

**Comment by mattfarina** [comment]
Unfortunately, it does not yet work on Apple Silicon. #16 was filed early on for support. We've looked into what we need to do for the support but have not yet built it.

**Comment by gaktive** [comment]
As noted, https://github.com/rancher-sandbox/rd/issues/16 will track our planned work on Silicon/M1. Closing this as a duplicate.
