### ISSUE TITLE
RD does not support locally installed trusted CA roots

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rd#249]
A user behind a corporate content filter reported this error:

```
FetchError: request to https://api.github.com/repos/k3s-io/k3s/releases?per_page=100 failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```

The company CA root is registered in the local keychain (otherwise the browsers wouldn't work), but RD seems not to recognize them

**Comment by jandubois** [comment]
It looks like nodejs does indeed not load certificates from the local trust stores, but instead has a compiled-in static list.

Maybe [Get Mac OS Root certificates in node.js](https://github.com/jfromaniello/mac-ca) can be used to fix this issueon macOS, and [Get Windows System Root certificates](https://github.com/ukoloff/win-ca) on Windows?

**Comment by pulberg** [comment]
I guess i'll wait for the next release as attempting to build src has run into numerous errors, ironically, including npm complaining about self-signed cert. 🤦

**Comment by jandubois** [comment]
We should have a new release soon, but if you attempt to build from source, you have to use npm 14; there is some compatibility issue with npm 16.

**Comment by pulberg** [comment]
Oh yes, i found all of those v16 issues 😂

**Comment by jandubois** [comment]
@pulberg [v0.2.0](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v0.2.0) with the fix is now available.

**Comment by br549times3** [comment]
I am getting this error in linux.
