### ISSUE TITLE
Allow the user to exit the app when docker-machine-driver-hyperkit cannot be made suid

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rd#258]
As part of the first-run setup we have to change the owner of `docker-machine-driver-hyperkit` to `root` and set the `suid` bit, so it can configure the vmnet settings.

This might throw an error when the app has not been installed into the `/Applications` directory, or anywhere else on the boot partition, but is being run from a volume that has been mounted without the `suid` bit. It will throw an error:

```console
sh -c 'chown root "/Volumes/Rancher Desktop 0.1.0/Rancher Desktop.app/Contents/Resources/resources/darwin/docker-machine-driver-hyperkit" && chmod u+s "/Volumes/Rancher Desktop 0.1.0/Rancher Desktop.app/Contents/Resources/resources/darwin/docker-machine-driver-hyperkit" && chown :admin "/Volumes/Rancher Desktop 0.1.0/Rancher Desktop.app/Contents/Resources/resources/darwin/hyperkit"'
2: Child exited with code undefined
Kubernetes was unable to start with exit code: undefined
```

But it will also prevent you from terminating the app, as the same dialog will be displayed over and over like it's Hotel California: You can checkout any time, but you can never leave! 😄

Well, "Force quit..." to the rescue, but terminating the app in this case should not try again to make `docker-machine-driver-hyperkit` be `suid`.

See also https://github.com/rancher-sandbox/rd/issues/253#issuecomment-832303942

**Comment by mook-as** [comment]
I'm going to treat this as "Cannot quit the application if we fail to stop the backend", and fix that.
