### ISSUE TITLE
Installer reboots Windows without warning

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rd#282]
I ran the latest installer on a Windows Pro machine that already had WSL2, Docker Desktop, Ubuntu and openSUSE distros installed.

I got the UAC prompt asking me if I want to let the installer modify my Windows settings, which I confirmed. After a little while it automatically rebooted the VM without asking for confirmation.

1. I don't understand why it had to reboot the machine, as WSL2 was already installed.
2. We should *never* reboot a machine without getting explicit user confirmation first.

I've uninstalled and reinstalled Rancher Desktop, but could no longer repro the reboot behaviour. I may fetch a copy of last night's backup to see if I can repro there.

Also noticed that uninstall doesn't actually remove the RD data, which can be much larger than the app itself (the cached k3s versions plus container images).

**Comment by jandubois** [comment]
Confirmed! First I get this prompt:

<img width="462" alt="Screen Shot 2021-05-12 at 6 37 38 PM" src="https://user-images.githubusercontent.com/78947/118065227-7913dd80-b351-11eb-9df4-c95ac5494919.png">

And then this one:

<img width="497" alt="Screen Shot 2021-05-12 at 6 37 54 PM" src="https://user-images.githubusercontent.com/78947/118065250-88932680-b351-11eb-9c2a-a8a6eef2c190.png">

which stays on the screen for a long time. Then another installer dialog pops up (which I haven't been able to capture, or even read), and then the machine reboots by itself.

**Comment by jandubois** [comment]
I've been running this experiment several more times, and I've been able to capture the additional dialog now:

<img width="450" alt="Screen Shot 2021-05-12 at 6 46 24 PM" src="https://user-images.githubusercontent.com/78947/118066327-613d5900-b353-11eb-96f0-6d040d3b9be9.png">

In this latest run I also opened Notepad and started writing some text. Having unsaved content in an open app did **not** prevent the reboot, or trigger another confirmation prompt.

This potential for users to lose unsaved work makes this bug much more serious!

**Comment by jandubois** [comment]
I've added this bug to the `v0.2.0` milestone: This behaviour must be either fixed or backed out before the release; causing dataloss to the user is unacceptable.

**Comment by jandubois** [comment]
Ok, so now I'm confused and/or impressed: it looks like Notepad was still running with the unsaved data after the reboot, so data has not been lost. I guess this needs additional investigation to determine if the potential for dataloss is real or not.

(I still think we should always ask before a reboot, but if there is no data loss, then it may not be a release blocker)

**Comment by mook-as** [comment]
I suspect that the notepad thing might just be notepad being too smart. But I think I see the state you need to be in to have the error, thanks to your additional screenshot in https://github.com/rancher-sandbox/rd/issues/282#issuecomment-840229406
- WSL is installed
- You've never installed the [kernel update](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)

I'll take this.

**Comment by jandubois** [comment]
> I suspect that the notepad thing might just be notepad being too smart.

Yeah, this is not your grandfather's Notepad anymore. 😄 

I redid the test with unsaved changes in Emacs. While I could recover the changes via the Emacs auto-save feature and using `M-x recover-files`, it shows that generally unsaved content is not preserved by the OS.
