### ISSUE TITLE
k3s on Mac

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#6]
The current setup on mac uses minikube and the default image. k3s should be the running Kuberentes. There are a couple possible ways this could be done.

1. Using hyperkit start a VM and then install k3s there. Note, the following 3 requirements are needed for this setup...
    1. Any version of k3s needs to be able to be run.
    2. The setup needs to have the ability to reset the environment to default (wipes out any config changes and all workloads are gone).
    3. Upgrades need to work. For example, one could go from 1.16.8 to 1.18.4 while retaining workloads running in the cluster.
2. Use flags like the `--iso-url` and registry location to swap out the default minikube environment for k3s.

**Comment by jandubois** [comment]
Is there a plan to use k3os, or should this be just any minimal vm image, and k3s is managed by RD?

I assume if you want to retains workloads across k3s updates, then using a non-changing OS layer is easier.

What is the plan for updating the host OS (e.g. for CVEs)? Does that need to retain workloads as well?

**Comment by mattfarina** [comment]
> Is there a plan to use k3os, or should this be just any minimal vm image, and k3s is managed by RD?

I don't care if k3os is used. k3s is the important part. The OS should be minimal. We'd talked about [flatcar](https://www.flatcar-linux.org/) linux at one point. It doesn't have to be a SUSE flavor of linux. It needs to be a right linux distro for the use.

> I assume if you want to retains workloads across k3s updates, then using a non-changing OS layer is easier.

Retaining workloads on upgrade is a requirement.

> What is the plan for updating the host OS (e.g. for CVEs)? Does that need to retain workloads as well?

Workloads need to be retained as well. Have not had a plan. Doesn't minikube handle that for you as well?

Note, Darren has talked about making k3s available via Minikube as an in general thing. I wonder if there is another use case beyond this.

**Comment by jandubois** [comment]
The easiest way I've [found](https://itnext.io/run-kubernetes-on-your-machine-7ee463af21a2) to setup k3s on macOS was using [multipass](https://github.com/canonical/multipass) (which also just uses hyperkit internally):

```
$ cat k3s.sh
#!/usr/bin/env bash
set -x
multipass launch --name k3s
multipass exec k3s -- bash -c "curl -sfL https://get.k3s.io | sh -"
multipass exec k3s sudo cat /etc/rancher/k3s/k3s.yaml > k3s.yaml
IP=$(multipass info k3s | grep IP | awk '{print $2}')
sed -i '' "s/127.0.0.1/$IP/" k3s.yaml
export KUBECONFIG=$PWD/k3s.yaml
sleep 5
kubectl cluster-info
```

It consistently creates a VM and installs `k3s` in under 50s (assuming the image is already downloaded):

```
$ time ./k3s.sh
+ multipass launch --name k3s
Launched: k3s
+ multipass exec k3s -- bash -c 'curl -sfL https://get.k3s.io | sh -'
[INFO]  Finding release for channel stable
[INFO]  Using v1.19.4+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.4+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.4+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
+ multipass exec k3s sudo cat /etc/rancher/k3s/k3s.yaml
++ multipass info k3s
++ grep IP
++ awk '{print $2}'
+ IP=192.168.64.7
+ sed -i '' s/127.0.0.1/192.168.64.7/ k3s.yaml
+ export KUBECONFIG=/Users/jan/tmp/k3s.yaml
+ KUBECONFIG=/Users/jan/tmp/k3s.yaml
+ sleep 5
+ kubectl cluster-info
Kubernetes master is running at https://192.168.64.7:6443
CoreDNS is running at https://192.168.64.7:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://192.168.64.7:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

real	0m49.524s
user	0m0.163s
sys	0m0.105s
```

Time passes...

```
$ kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   metrics-server-7b4f8b595-sfk58           1/1     Running     0          2m
kube-system   local-path-provisioner-7ff9579c6-66xlr   1/1     Running     0          2m
kube-system   coredns-66c464876b-cmknb                 1/1     Running     0          2m
kube-system   helm-install-traefik-2jjwh               0/1     Completed   0          2m
kube-system   svclb-traefik-h75j7                      2/2     Running     0          1m41s
kube-system   traefik-5dd496474-r79pd                  1/1     Running     0          1m41s
```

**Comment by jandubois** [comment]
> The easiest way I've found to setup k3s on macOS

That was meant to include "without using docker". Otherwise the answer would obviously have been `k3d`.

**Comment by mattfarina** [comment]
Unfortunately, multipass is GPLv3 licensed.

We only need hyperkit for Mac. On Windows we'll use WSL so it can work on Windows Home. If we get setup on Linux we can use the OS directly (maybe). I wonder if we could use hyperkit directly or write a small wrapper around it. Then use that on Mac. Thoughts?

**Comment by jandubois** [comment]
> Unfortunately, multipass is GPLv3 licensed.

Can you explain why this is an issue? As long as you keep it a separate app, you should always be able to aggregate it with and use it from other applications that might have a different license.

**Comment by mattfarina** [comment]
Closed as first pass is complete
